---
- name: Remove kernel headers package
  ansible.builtin.apt:
    name: "{{ ovos_hardware_mark2_kernel_headers_package }}"
    state: absent
    purge: true
    autoremove: true
  failed_when: false
  when:
    - ovos_installer_uninstall_remove_packages | default(false) | bool
    - ansible_facts.os_family == "Debian"
