---
- name: Include tuning/eeprom.yml
  ansible.builtin.import_tasks: eeprom.yml

- name: Include tuning/governor.yml
  ansible.builtin.import_tasks: governor.yml

- name: Include tuning/io.yml
  ansible.builtin.import_tasks: io.yml

- name: Include tuning/zram.yml
  vars:
    # Debian Unstable hack
    _distribution_version: "{{ '99' if ansible_facts.distribution == 'Debian' and ansible_facts.distribution_version == 'n/a' else ansible_facts.distribution_version }}"
  ansible.builtin.import_tasks: zram.yml
  when:
    - not (ansible_facts.distribution == 'Ubuntu' and _distribution_version is version('23.04', '<=') or
           ansible_facts.distribution == 'Debian' and _distribution_version is version('12.0', '<='))

- name: Include tuning/sysctl.yml
  ansible.builtin.import_tasks: sysctl.yml

- name: Include tuning/numa.yml
  ansible.builtin.import_tasks: numa.yml

- name: Include tuning/memory.yml
  ansible.builtin.import_tasks: memory.yml

- name: Include tuning/limits.yml
  ansible.builtin.import_tasks: limits.yml
