---
- name: Gather network interface facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "network"

- name: Include tuning/wireless.yml
  ansible.builtin.import_tasks: wireless.yml
  when:
    - ansible_facts['wlan0'] is defined
    - ansible_facts['wlan0'].active | bool

- name: Include tuning/dns.yml
  ansible.builtin.import_tasks: dns.yml
