---
- name: Include assert.yml
  ansible.builtin.import_tasks: assert.yml
  tags:
    - always

- name: Include uninstall tasks
  ansible.builtin.import_tasks: uninstall.yml
  when: ovos_network_tuning_is_cleaning | bool
  tags:
    - uninstall

- name: Stop network tuning install flow while cleaning
  ansible.builtin.meta: end_role
  when: ovos_network_tuning_is_cleaning | bool

- name: Include tuning/wireless.yml
  ansible.builtin.import_tasks: wireless.yml
  when:
    - ansible_facts['wlan0'] is defined
    - ansible_facts['wlan0'].active | bool

- name: Include tuning/dns.yml
  ansible.builtin.import_tasks: dns.yml
