---
- name: Remove NetworkManager dnsmasq config
  ansible.builtin.file:
    path: "{{ ovos_network_tuning_dnsmasq_conf_path }}"
    state: absent
  when: ovos_installer_networkmanager_dir.stat.exists | default(false) | bool
  notify: Restart NetworkManager

- name: Remove dnsmasq cache config
  ansible.builtin.file:
    path: "{{ ovos_network_tuning_dnsmasq_cache_conf_path }}"
    state: absent
  when: ovos_installer_networkmanager_dir.stat.exists | default(false) | bool
  notify: Restart NetworkManager

- name: Find wireless power systemd units
  ansible.builtin.find:
    paths: "{{ ovos_installer_systemd_system_path | default('/etc/systemd/system') }}"
    patterns: "wl*-power.service"
    file_type: file
  register: ovos_network_tuning_wireless_units
  changed_when: false

- name: Stop and disable wireless power systemd units
  ansible.builtin.systemd_service:
    name: "{{ item.path | basename }}"
    enabled: false
    state: stopped
  failed_when: false
  loop: "{{ ovos_network_tuning_wireless_units.files | default([]) }}"
  loop_control:
    label: "{{ item.path | basename }}"

- name: Remove wireless power systemd unit files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ ovos_network_tuning_wireless_units.files | default([]) }}"
  notify: Reload Systemd

- name: Flush handlers wireless (uninstall)
  ansible.builtin.meta: flush_handlers
