name: Testing shell components with BATS

permissions:
  contents: read

on:
  pull_request:
    paths:
      - .github/workflows/shell_testing.yml
      - .github/scripts/**
      - setup.sh
      - utils/**
      - tui/**
      - tests/bats/**
  push:
    paths:
      - .github/workflows/shell_testing.yml
      - .github/scripts/**
      - setup.sh
      - utils/**
      - tui/**
      - tests/bats/**
  workflow_dispatch:

jobs:
  shell-testing:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install BATS requirements
        run: |
          sudo apt-get update
          sudo apt-get --no-install-recommends install -y bats git ca-certificates

      - name: Install BATS helper libraries
        run: ./.github/scripts/install_bats_helpers.sh

      - name: Run bats
        run: bats tests/bats --verbose-run --print-output-on-failure
